### ISSUE TITLE
Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by LunixWasTaken** [jaredwray/keyv#117]
I recently had a lot of troubles when using Kevy over a long term > 12 hours and i'm not sure if that's supposed to be caught by keyv.on 'error'

db.on('error', err => console.error('Keyv connection error:', err));

is not being sent in the logs

instead it sends

```
Error: Can't add new command when connection is in closed state
    at PromiseConnection.execute (/home/aid-bot/lunix-aid/node_modules/mysql2/promise.js:102:20)
    at /home/aid-bot/lunix-aid/node_modules/@keyv/mysql/src/index.js:19:30
    at /home/aid-bot/lunix-aid/node_modules/@keyv/sql/src/index.js:39:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  errno: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}

```

so far i haven't been able to find a workaround or the immediate cause.

**Comment by capwizz** [comment]
I'm having the same issue. However before this error message persist, I receive this error:

`Error: This socket has been ended by the other party`

**Comment by cjcanlas01** [comment]
Any news about this? Having the same issue on a Heroku deployment.

```
2022-02-01T04:10:57.029289+00:00 app[worker.1]: Error: Can't add new command when connection is in closed state
2022-02-01T04:10:57.029298+00:00 app[worker.1]:     at PromiseConnection.execute (/app/node_modules/@keyv/mysql/node_modules/mysql2/promise.js:102:20)
2022-02-01T04:10:57.029298+00:00 app[worker.1]:     at /app/node_modules/@keyv/mysql/src/index.js:19:30
2022-02-01T04:10:57.029299+00:00 app[worker.1]:     at /app/node_modules/@keyv/sql/src/index.js:39:19
2022-02-01T04:10:57.029300+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2022-02-01T04:10:57.029301+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Package version:
`"keyv": "^4.0.3"`

And any workaround I can do to avoid this for the meantime? Thanks.
