### ISSUE TITLE
Getting error SQLITE_BUSY

### ISSUE THREAD

**Issue by arthurvanl** [jaredwray/keyv#177]
I keep getting this error.
```
[Error: SQLITE_BUSY: database is locked] {
  errno: 5,
  code: 'SQLITE_BUSY'
}
/root/lucid/node_modules/@keyv/sql/src/index.js:39
			.then(query => query(sqlString));
			               ^

TypeError: query is not a function
    at /root/lucid/node_modules/@keyv/sql/src/index.js:39:19
    at async DatabaseManager.get (/root/lucid/functions/connectDatabase.js:24:20)
    at async /root/lucid/functions/testing.js:16:22
```

Is there a way to handle this or close connections cause it seems that i cant close connections.

**Comment by jaredwray** [comment]
@arthurvanl - have you tried to access the storage adapter via `opts.store` to close and re-open? 

Also, you can set the busy timeout via the options:

```javascript
const keyv = new Keyv('sqlite://path/to/database.sqlite', {
  table: 'cache',
  busyTimeout: 10000
});
```

**Comment by arthurvanl** [comment]
Busy timeout is that after that time the connection has been closed???

**Comment by jaredwray** [comment]
@arthurvanl - do you have a code example that triggers this so I can help out?

**Comment by arthurvanl** [comment]
Im just asking if it closes the connection or not with `busyTimeout`

**Comment by jaredwray** [comment]
@arthurvanl it does not close the connection.

**Comment by arthurvanl** [comment]
Where is it used for then?

**Comment by jaredwray** [comment]
@arthurvanl - here is a good overview of what it does: https://sqlite.org/c3ref/busy_timeout.html

```
This routine sets a busy handler that sleeps for a specified amount of time when a table is locked. The handler will sleep multiple times until at least "ms" milliseconds of sleeping have accumulated. After at least "ms" milliseconds of sleeping, the handler returns 0 which causes sqlite3_step() to return SQLITE_BUSY.
```

**Comment by arthurvanl** [comment]
So there is no way to close connection after a specific amount of time

**Comment by jaredwray** [comment]
After passing in options you can then access the db object and do a `options.db.close();`

**Comment by arthurvanl** [comment]
Im not sure what you mean, cant i just use @keyv/sqlite as the store & close the connections from that. Do you have an code example.

**Comment by jaredwray** [comment]
Yep. This should work:

```javascript
const options =  {
  table: 'cache',
  busyTimeout: 10000
};
const keyv = new Keyv('sqlite://path/to/database.sqlite', options);

options.db.close(); //this will close the connection
```

**Comment by arthurvanl** [comment]
Oke thanks!

**Comment by arthurvanl** [comment]
```
C:\Users\arthu\Desktop\programs\ranked_bedwars\commands\general\register.js:30
            let closed = await db.options.db.close();
                                             ^

TypeError: Cannot read property 'close' of undefined
    at Object.execute (C:\Users\arthu\Desktop\programs\ranked_bedwars\commands\general\register.js:30:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
    
I get an error
```js
        this.options = {
            table: 'cache', 
            busyTimeout: 10000
        }
        this.database = new Keyv(`sqlite://${process.cwd()}/database.sqlite`, this.options);
```
    What did i wrong?

**Comment by jaredwray** [comment]
Based on what I am seeing I would guess it would be:

```
this.options.db.close();
```

**Comment by arthurvanl** [comment]
Yea i did that jared, i created as an class so i did the same, but it doesnt work, its not an option in the options object.

**Comment by arthurvanl** [comment]
But that would be kinda logic right,  because 

```js
class DatabaseManager {

    constructor(){
        this.options = {
            table: 'cache', 
            busyTimeout: 10000
        }
        this.database = new Keyv(`sqlite://${process.cwd()}/database.sqlite`, this.options);
        this.database.on('error', (err) => console.log(`[${moment().format("HH:mm:ss")}] Error with connection database: ${err.message}`))
    }
    ```
In the options, there is only table & busyTimeout, no other functional options.

**Comment by arthurvanl** [comment]
Owh, oke..
