### ISSUE TITLE
Open handle keeping Jest from exiting

### ISSUE THREAD

**Issue by rafagsiqueira** [jaredwray/keyv#403]
**Describe the bug**
I have been trying to use keyv on a Jest unit test. The test runs but Jest complains in the end:
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TLSWRAP

       5 | export class Cache {
       6 |
    >  7 |   private client = new Keyv(process.env.REDIS_CONNECTION_STRING);
```
I have tried all sorts of approaches to "close" the handle. By calling keyv.disconnect(), by calling keyv.redis.quit(), but I keep getting errors saying the connection is already closed.

```
/Users/rafasiqueira/Work/etips-api/node_modules/ioredis/built/redis/event_handler.js:182
        self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                        ^
Error: Connection is closed.
    at close (/Users/rafasiqueira/Work/etips-api/node_modules/ioredis/built/redis/event_handler.js:182:25)
    at TLSSocket.<anonymous> (/Users/rafasiqueira/Work/etips-api/node_modules/ioredis/built/redis/event_handler.js:149:20)
    at Object.onceWrapper (node:events:652:26)
    at TLSSocket.emit (node:events:549:35)
    at node:net:747:14
    at TCP.done (node:_tls_wrap:582:7)
```
**To Reproduce**
```
let client = new Keyv(process.env.REDIS_CONNECTION_STRING);
private keyAdapter = new KeyvAdapter(this.client);
public faultTolerantCache = new ErrorsAreMissesCache(this.keyAdapter);

const serverOptions: ApolloServerExpressConfig = {
      schema: subgraphSchema,
      dataSources,
      context,
      plugins: [ApolloServerPluginInlineTraceDisabled()],
      cache: faultTolerantCache

let server: ApolloServer; 

beforeAll(() => {
    server = new ApolloServer(serverOptions);
});

  afterAll((done) => {
    client.disconnect().then(() => done());
  });

  it('fetches mtdsg action', (done) => {
    server.executeOperation({
      query: GET_ACTION,
      variables: { id: '080000028047f4a3' }
    })
    .then((result) => {
      expect(result.errors).toBeUndefined();
      done();
    });
  });

**Expected behavior**
The test should pass and Jest should exit.

**Comment by jaredwray** [comment]
Hi @rafagsiqueira - thanks and we are looking into this.

**Comment by alphmth** [comment]
@rafagsiqueira I tried with code in this [gist](https://gist.github.com/alphmth/3a7c41302e808bb726f588436c9b003b)

Jest works. Can you share your code so that I can take a look?

**Comment by jaredwray** [comment]
@rafagsiqueira - let us know if you are able to figure this out and give us a repro step and we will re-open this issue.

**Comment by rafagsiqueira** [comment]
Could it be the imports, instead of the requires?
```
import KeyvRedis from '@keyv/redis';
import Keyv from 'keyv';

let cache;

  beforeAll(async () => {
    const keyvRedis = new KeyvRedis(process.env.REDIS_CONNECTION_STRING);
    cache = new Keyv({store: keyvRedis});
  });

  afterAll(async () => {
    await cache.disconnect();
  });

  it('testing cache', async () => {
    await cache.set('foo', 'bar');
    expect(await cache.get('foo')).toBe('bar');
  });
```
I am still getting the following error:
```
TLSWRAP

      136 |
      137 |   beforeAll(async () => {
    > 138 |     const keyvRedis = new KeyvRedis(process.env.REDIS_CONNECTION_STRING);
          |                       ^
      139 |     cache = new Keyv({store: keyvRedis});
      140 |   });
      141 |

      at node_modules/ioredis/built/connectors/StandaloneConnector.js:44:21
      at StandaloneConnector.connect (node_modules/ioredis/built/connectors/StandaloneConnector.js:43:16)
      at node_modules/ioredis/built/Redis.js:121:64
      at EventEmitter.connect (node_modules/ioredis/built/Redis.js:103:25)
      at new Redis (node_modules/ioredis/built/Redis.js:77:18)
      at new KeyvRedis (node_modules/@keyv/redis/src/index.js:15:17)
```

**Comment by rafagsiqueira** [comment]
No, I get the same error using require. Could this be related to TLS? My redis string is rediss://

**Comment by rafagsiqueira** [comment]
Yes. It works without TLS.

**Comment by alphmth** [comment]
@rafagsiqueira are you using self-signed certificate? I added `NODE_TLS_REJECT_UNAUTHORIZED='0'  jest` and it works for me with tls as well

**Comment by rafagsiqueira** [comment]
@alphmth, thank you for your help on this. Setting NODE_TLS_REJECT_UNAUTHORIZED='0' doesn't change the error. I am on node v18.4.0.

**Comment by alphmth** [comment]
@rafagsiqueira can you share a test repo with error. I am not able to reproduce the issue

**Comment by jaredwray** [comment]
@rafagsiqueira - we are not able to reproduce this issue. Going to close this out for now.

**Comment by rafagsiqueira** [comment]
Sorry, I ended up removing the cache from my unit tests.
