### ISSUE TITLE
[QUESTION]: Cannot read property 'expires' of null when using iterator

### ISSUE THREAD

**Issue by simplecommerce** [jaredwray/keyv#623]
Hi,

I am using Keyv with KeyvAdapter for my @apollo/server instance so I can use it as a caching backend with Redis.

I followed these simple steps: https://www.apollographql.com/docs/apollo-server/performance/cache-backends#single-instance

In my code, I need to loop through the cache and remove some entries using a specific logic, so I followed the example using the iterator by running the following code: (this.cache.keyv, is the path I need to put to access the instance)

```
// please note that the "await" keyword should be used here
for await (const [key, value] of this.cache.keyv.iterator()) {
	console.log(key);
}
```

For some reason I am running into this problem:

```
TypeError: Cannot read property 'expires' of null
    at Keyv.iterator (/root/v3/laverendrye/laverendrye/graphql/node_modules/keyv/src/index.js:74:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Logs.deleteFromCacheStartsWith (/root/v3/laverendrye/laverendrye/graphql/api/datasources/mongo/datasource.js:225:3) Unhandled Rejection at Promise Promise {
  <rejected> TypeError: Cannot read property 'expires' of null
      at Keyv.iterator (/root/v3/laverendrye/laverendrye/graphql/node_modules/keyv/src/index.js:74:21)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at Logs.deleteFromCacheStartsWith (/root/v3/laverendrye/laverendrye/graphql/api/datasources/mongo/datasource.js:225:3)
}
```

It seems to loop fine for some entries but keeps throwing this error on some others.
I put a try catch block around it and at least I can suppress the error.

I did some further testing and I noticed that in my code if I delete the entry from the cache and then iterate, it will cause the error.

```
this.keyv.delete(key);  // in some cases I have the specific key to delete

// but I also need to remove some related entries that I don't have a specific key for, so I need to loop through the cache and remove them
for await (const [key, value] of this.cache.keyv.iterator()) {

}
```

I put a `console.log(this.opts.store.namespace, key, data)` in the `generateIterator` function to see its output)
I end up with something like this: 
```
cache cache:mongo-laverendrye_dev-people-63173ee2df60f1a2ac93c2ed null // this entry was removed first and is still in the cache but with null)
cache cache:namespace:keyv null // this I have no idea where it comes from
```

Ok, I just realized that if I want to prevent an error, I need to await my initial delete before iterating.
I am still left with the `cache cache:namespace:keyv null` which I have no idea where it comes from.

Am I missing something?

Thanks!

**Comment by simplecommerce** [comment]
Ok, I figured out my issue, it was because initially I didn't provide a namespace and changed it afterwards.
I rebooted my redis instance and i no longer see the weird namespace issue.
